### ISSUE TITLE
sorting: fix exports in index.js

### ISSUE THREAD

**Issue by javierfurus** [flowacademyhu/prog-basic-catalog#55]
Exports should look like this:
minimumSelectionSort: minimumSelectionSort.minimumSelectionSort

Otherwise the following thing will be passed to main.js:
require('./minimumSelectionSort');
Which is not a function!

FIXED:
My method is just one way to solve this problem, your Index file works fine now. :)

**Comment by Redturtle42** [comment]
Please check the fixes Javier!
If you import the module into main.js - for example as 'cica' - you can call the function like cica.bubble.sort().  :)
Is it good for you?
