### ISSUE TITLE
part1: fix exports in index.js

### ISSUE THREAD

**Issue by javierfurus** [flowacademyhu/prog-basic-catalog#56]
Exports should look like this:
minimumSelectionSort: minimumSelectionSort.minimumSelectionSort

Otherwise the following thing will be passed to main.js:
require('./minimumSelectionSort');
Which is not a function!
FIXED:
My method is just one way to solve this problem, your Index file works fine now. :)

**Comment by Redturtle42** [comment]
Minimum Selection Sort was the task of team3. It has been fixed. So this ticket is unnecesarry. (I think so.)

**Comment by javierfurus** [comment]
Sorry, minimum selection was just an example, but the issue has been resolved. :D
